### ISSUE TITLE
执行sql时，未正确传递参数

### ISSUE THREAD

**Issue by myl0204** [react-native-oh-library/react-native-sqlite-storage#9]
前两天有和你们沟通过，请问什么时候能修复并发布新版？

或者我可以发起一个PR

具体问题有：
1. 参数未传递 （包括INSERT、UPDATE、SELECT等操作）
2. DROP执行失败

**Comment by ding-chengjie** [comment]
已经修复合入

**Comment by myl0204** [comment]
> 已经修复合入

请问新版什么时候release

**Comment by ding-chengjie** [comment]
已经发布了新版了
